name: dartcade
description: A simple set of terminal-based arcade games written in pure Dart.
version: 0.1.0
homepage: https://github.com/neo-dart/dartcade

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  griddle: ^0.3.1
  meta: ^1.7.0
  neokeys: ^0.1.1
  stack_trace: ^1.10.0

dev_dependencies:
  neodart: ^0.1.1

executables:
  pong:
